services:
  iowarp:
    image: lukemartinlogan/chimaera-deps:latest
    container_name: iowarp  
    shm_size: 8g
    mem_limit: 8g
    volumes:
      - ${IOWARP_PKGS}/cte-hermes-shm:/cte-hermes-shm
      - ${IOWARP_PKGS}/iowarp-runtime:/iowarp-runtime
      - ${IOWARP_PKGS}/content-transfer-engine:/content-transfer-engine
    stdin_open: true
    tty: true
    network_mode: host