package:
  name: chimaera
  version: 0.0.0

source:
   path: .
#  git_url: https://github.com/hyoklee/iowarp-runtime
#  git_depth: 1

requirements:
  build:
    - numpy
    - panda
    - scipy
    - scikit-learn
    - setuptools
    - iowarp::scspkg
  run:
    - iowarp::scspkg

test:
  requires:
    - numpy
    - pandas    
    - scipy
    - scikit-learn
    - setuptools
    - iowarp::scspkg  
  commands:
    - bench_chimaera_latency 0 1000 0

about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp Chimaera Conda Package
