package:
  name: chimaera
  version: 0.0.0

source:
#  git_url: https://github.com/hyoklee/iowarp-runtime
#  git_depth: 1
  path: .

requirements:
  build:
    - autoconf
    - boost
    - json-c
    - numpy
    - openmp
    - openmpi
    - pandas
    - pybind11
    - scipy
    - scikit-learn
    - snappy
    - iowarp::argobots
    - iowarp::margo    
    - iowarp::mercury
    - iowarp::scspkg    
  run:
    - python
    - iowarp::argobots
    - iowarp::margo
    - iowarp::mercury    
    - iowarp::scspkg
test:
  requires:
    - autoconf
    - boost
    - json-c
    - numpy
    - openmp
    - openmpi
    - pandas
    - pybind11
    - scipy
    - scikit-learn
    - snappy
    - iowarp::scspkg
    - iowarp::margo
    - iowarp::argobots    
  commands:
    - pip --help

about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp chimaera Conda Package
