package:
  name: chimaera
  version: 0.0.0

source:
#  git_url: https://github.com/hyoklee/iowarp-runtime
#  git_depth: 1
  path: .

requirements:
  build:
    - autoconf
    - boost
    - json-c
    - numpy
    - openmp
    - openmpi
    - pandas
    - pybind11
    - scipy
    - scikit-learn
    - snappy
    - iowarp::scspkg
    - iowarp::margo
  run:
    - python
    - iowarp::scspkg
    - iowarp::margo
test:
  requires:
    - autoconf
    - boost
    - json-c
    - numpy
    - openmp
    - openmpi
    - pandas
    - pybind11
    - scipy
    - scikit-learn
    - snappy
    - iowarp::scspkg
    - iowarp::margo    
  commands:
    - bench_chimaera_latency 0 1000 0

about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp chimaera Conda Package
