name: lin

on:
  workflow_dispatch:
  push:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          sudo apt -y install lmod elfutils
          . ./ci.sh
          pip --version
          pip install -r requirements.txt
          . ./env.sh
          cmake -B build .
          make -C build -j
